name: ai_assistant
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # For using lottie animation
  lottie: ^2.7.0

  # For Hive Database
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13

  # For Accessing Storage Path
  path_provider: ^2.1.1

  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # For changes app icon
  icons_launcher: ^2.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
